AllCops:
  Exclude:
    - db/schema.rb
    - db/seeds.rb
    - node_modules/**/*
    - public/js/ext/**/*
    - vendor/bundle/**/*
    - tmp/**/*

LineLength:
  Max: 130

MethodLength:
  Max: 20

AbcSize:
  Enabled: false

AsciiComments:
  Enabled: false

Documentation:
  Enabled: false

Style/RegexpLiteral:
  MaxSlashes: 0
