AllCops:
  Exclude:
    - db/schema.rb
    - node_modules/**/*
    - public/js/ext/**/*

LineLength:
  Max: 130

MethodLength:
  Max: 20

AsciiComments:
  Enabled: false

Documentation:
  Enabled: false
