AllCops:
  Exclude:
    - db/schema.rb
    - db/seeds.rb
    - node_modules/**/*
    - public/js/ext/**/*
    - bin/**/*
    - config/**/*
    - vendor/**/*
    - tmp/**/*
  DisplayCopNames: true

LineLength:
  Max: 130

MethodLength:
  Max: 20

AbcSize:
  Enabled: false

AsciiComments:
  Enabled: false

Documentation:
  Enabled: false

Style/RegexpLiteral:
  AllowInnerSlashes: false

NumericLiterals:
  MinDigits: 7

ShadowingOuterLocalVariable:
  Enabled: false

GuardClause:
  MinBodyLength: 4
