ap-northeast-1:
  platform: centos
  image: ami-048c826a
ap-northeast-2:
  platform: centos
  image: ami-757db31b
ap-southeast-1:
  platform: centos
  image: ami-4963ab2a
ap-southeast-2:
  platform: centos
  image: ami-4ad6f729
eu-west-1:
  platform: centos
  image: ami-2921995a
eu-central-1:
  platform: centos
  image: ami-7c16f213
sa-east-1:
  platform: centos
  image: ami-049b1668
us-east-1:
  platform: centos
  image: ami-72a8a918
us-west-1:
  platform: centos
  image: ami-9dabd8fd
us-west-2:
  platform: centos
  image: ami-ea58b78a
