ap-northeast-1:
  platform: centos
  image: ami-31d0df5f
ap-northeast-2:
  platform: centos
  image: ami-c0509eae
ap-southeast-1:
  platform: centos
  image: ami-d32be3b0
ap-southeast-2:
  platform: centos
  image: ami-f0092893
eu-west-1:
  platform: centos
  image: ami-062f9675
eu-central-1:
  platform: centos
  image: ami-72e5011d
sa-east-1:
  platform: centos
  image: ami-63df520f
us-east-1:
  platform: centos
  image: ami-b690abdc
us-west-1:
  platform: centos
  image: ami-f1700391
us-west-2:
  platform: centos
  image: ami-6a937c0a
