ap-northeast-1:
  platform: centos
  image: ami-deefefb0
ap-southeast-1:
  platform: centos
  image: ami-aae22bc9
ap-southeast-2:
  platform: centos
  image: ami-4d51772e
eu-west-1:
  platform: centos
  image: ami-0929947a
eu-central-1:
  platform: centos
  image: ami-8dcdd7e1
sa-east-1:
  platform: centos
  image: ami-d1c042bd
us-east-1:
  platform: centos
  image: ami-3640735c
us-west-1:
  platform: centos
  image: ami-d2ddacb2
us-west-2:
  platform: centos
  image: ami-969f7df6
