ap-northeast-1:
  platform: centos
  image: ami-d5f2f2bb
ap-northeast-2:
  platform: centos
  image: ami-eb26e885
ap-southeast-1:
  platform: centos
  image: ami-6408c107
ap-southeast-2:
  platform: centos
  image: ami-812c0ae2
eu-west-1:
  platform: centos
  image: ami-0ff9457c
eu-central-1:
  platform: centos
  image: ami-6ffce603
sa-east-1:
  platform: centos
  image: ami-2ce56740
us-east-1:
  platform: centos
  image: ami-18c5f672
us-west-1:
  platform: centos
  image: ami-48324228
us-west-2:
  platform: centos
  image: ami-abca28cb
