ap-northeast-1: ami-9b4b789a
ap-southeast-1: ami-0eb7965c
ap-southeast-2: ami-c50864ff
eu-west-1: ami-9210bee5
eu-central-1: ami-bc0234a1
sa-east-1: ami-ab0fbbb6
us-east-1: ami-74da531c
us-west-1: ami-5940541c
us-west-2: ami-575c1267
