ap-northeast-1:
  - platform: centos
    platform_version: 6.7
    source_image: ami-76131818
    ssh_username: centos
  - platform: centos
    platform_version: 7.2
    source_image: ami-b18c82df
    ssh_username: centos
ap-northeast-2:
  - platform: centos
    platform_version: 6.7
    source_image: ami-85925beb
    ssh_username: centos
  - platform: centos
    platform_version: 7.2
    source_image: ami-5476b83a
    ssh_username: centos
ap-southeast-1:
  - platform: centos
    platform_version: 6.7
    source_image: ami-ce15dead
    ssh_username: centos
  - platform: centos
    platform_version: 7.2
    source_image: ami-e362aa80
    ssh_username: centos
ap-southeast-2:
  - platform: centos
    platform_version: 6.7
    source_image: ami-2901214a
    ssh_username: centos
  - platform: centos
    platform_version: 7.2
    source_image: ami-16d0f175
    ssh_username: centos
eu-west-1:
  - platform: centos
    platform_version: 6.7
    source_image: ami-3be36648
    ssh_username: centos
  - platform: centos
    platform_version: 7.2
    source_image: ami-802c94f3
    ssh_username: centos
eu-central-1:
  - platform: centos
    platform_version: 6.7
    source_image: ami-650dea0a
    ssh_username: centos
  - platform: centos
    platform_version: 7.2
    source_image: ami-8d0aeee2
    ssh_username: centos
sa-east-1:
  - platform: centos
    platform_version: 6.7
    source_image: ami-3c32bf50
    ssh_username: centos
  - platform: centos
    platform_version: 7.2
    source_image: ami-5f991433
    ssh_username: centos
us-east-1:
  - platform: centos
    platform_version: 6.7
    source_image: ami-04f0f06e
    ssh_username: centos
  - platform: centos
    platform_version: 7.2
    source_image: ami-7eafaa14
    ssh_username: centos
us-west-1:
  - platform: centos
    platform_version: 6.7
    source_image: ami-7e6a181e
    ssh_username: centos
  - platform: centos
    platform_version: 7.2
    source_image: ami-84abd8e4
    ssh_username: centos
us-west-2:
  - platform: centos
    platform_version: 6.7
    source_image: ami-417a9321
    ssh_username: centos
  - platform: centos
    platform_version: 7.2
    source_image: ami-e85bb488
    ssh_username: centos
