# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: caf29387db8b8f1d830b97ee6581a46c47b6bec1dd3f5c50a7ce304624f045e7c38790dd1ccdfb6c5a0237252ecc11007a423322ebe87453fa42cf6a08bcf1ea

test:
  secret_key_base: caf29387db8b8f1d830b97ee6581a46c47b6bec1dd3f5c50a7ce304624f045e7c38790dd1ccdfb6c5a0237252ecc11007a423322ebe87453fa42cf6a08bcf1ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: caf29387db8b8f1d830b97ee6581a46c47b6bec1dd3f5c50a7ce304624f045e7c38790dd1ccdfb6c5a0237252ecc11007a423322ebe87453fa42cf6a08bcf1ea
