aws:
  name: "{{base_image `name`}}"
  type: "amazon-ebs"
  access_key: "{{cloud `key`}}"
  secret_key: "{{cloud `secret`}}"
  region: "{{cloud `entry_point`}}"
  instance_type: "c3.large"
  ami_name: "{{operating_system `name`}}-{{user `image_name`}}-{{uuid}}"
  ssh_username: "{{base_image `ssh_username`}}"
  source_ami: "{{base_image `source_image`}}"
  tags: {
    Name: "{{operating_system `name`}}-{{user `image_name`}}"
  }
  launch_block_device_mappings:
    - device_name: "/dev/sda1"
      delete_on_termination: true

openstack:
  name: "{{base_image `name`}}"
  type: "openstack"
  username: "{{cloud `key`}}"
  password: "{{cloud `secret`}}"
  project: "{{cloud `tenant_name`}}"
  provider: "{{cloud `entry_point`}}v2.0/tokens"
  region: "RegionOne"
  flavor: "2"
  image_name: "{{operating_system `name`}}-{{user `image_name`}}-{{uuid}}"
  source_image: "{{base_image `source_image`}}"
  ssh_username: "{{base_image `ssh_username`}}"
  use_floating_ip: "true"
  floating_ip_pool: "public"
